### ISSUE TITLE
Error when installing with npm 3

### ISSUE THREAD

**Issue by phw** [groupon/cson-parser#46]
When installing this package with npm 3 I get the following error:

```
$ npm install cson-safe
npm ERR! Linux 4.1.6-1-ARCH
npm ERR! argv "node" "/usr/bin/npm" "install" "cson-safe"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.3
npm ERR! code EREADFILE

npm ERR! Error extracting /home/phw/.npm/cson-safe/1.0.4/package.tgz archive: ENOENT, open '/home/phw/.npm/cson-safe/1.0.4/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/phw/tmp/nodetest/npm-debug.log
```

Installing with npm 2 works just fine. Not quite sure who is to blame here, npm or this package.

**Comment by phw** [comment]
Here is the output in npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'install', 'cson-safe' ]
2 info using npm@3.3.3
3 info using node@v0.12.7
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData cson-safe
8 silly fetchNamedPackageData cson-safe
9 silly mapToRegistry name cson-safe
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/cson-safe
13 verbose request uri https://registry.npmjs.org/cson-safe
14 verbose request no auth needed
15 info attempt registry request try #1 at 10:02:17
16 verbose request using bearer token for auth
17 verbose request id 6ea79dc3a4ad61e9
18 http request GET https://registry.npmjs.org/cson-safe
19 http 200 https://registry.npmjs.org/cson-safe
20 silly get cb [ 200,
20 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 silly get     etag: '"2C4Z1CE52B3S1B44MJLCQJMQG"',
20 silly get     'content-type': 'application/json',
20 silly get     'cache-control': 'max-age=60',
20 silly get     'content-length': '12597',
20 silly get     'accept-ranges': 'bytes',
20 silly get     date: 'Mon, 21 Sep 2015 08:02:18 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-lcy1126-LCY',
20 silly get     'x-cache': 'MISS',
20 silly get     'x-cache-hits': '0',
20 silly get     'x-timer': 'S1442822538.048482,VS0,VE171',
20 silly get     vary: 'Accept' } ]
21 verbose get saving cson-safe to /home/phw/.npm/registry.npmjs.org/cson-safe/.cache.json
22 silly install normalizeTree
23 silly loadCurrentTree Finishing
24 silly loadIdealTree Starting
25 silly install loadIdealTree
26 silly cloneCurrentTree Starting
27 silly install cloneCurrentTreeToIdealTree
28 silly cloneCurrentTree Finishing
29 silly loadShrinkwrap Starting
30 silly install loadShrinkwrap
31 silly loadShrinkwrap Finishing
32 silly loadAllDepsIntoIdealTree Starting
33 silly install loadAllDepsIntoIdealTree
34 silly resolveWithNewModule cson-safe@1.0.4 checking installable status
35 silly cache add args [ 'cson-safe', null ]
36 verbose cache add spec cson-safe
37 silly cache add parsed spec { raw: 'cson-safe',
37 silly cache add   scope: null,
37 silly cache add   name: 'cson-safe',
37 silly cache add   rawSpec: '',
37 silly cache add   spec: '*',
37 silly cache add   type: 'range' }
38 silly addNamed cson-safe@*
39 verbose addNamed "*" is a valid semver range for cson-safe
40 silly addNameRange { name: 'cson-safe', range: '*', hasData: false }
41 silly mapToRegistry name cson-safe
42 silly mapToRegistry using default registry
43 silly mapToRegistry registry https://registry.npmjs.org/
44 silly mapToRegistry uri https://registry.npmjs.org/cson-safe
45 verbose addNameRange registry:https://registry.npmjs.org/cson-safe not in flight; fetching
46 verbose get https://registry.npmjs.org/cson-safe not expired, no request
47 silly addNameRange number 2 { name: 'cson-safe', range: '*', hasData: true }
48 silly addNameRange versions [ 'cson-safe',
48 silly addNameRange   [ '0.1.0',
48 silly addNameRange     '0.1.1',
48 silly addNameRange     '0.2.0',
48 silly addNameRange     '1.0.0',
48 silly addNameRange     '1.0.1',
48 silly addNameRange     '1.0.2',
48 silly addNameRange     '1.0.3',
48 silly addNameRange     '1.0.4',
48 silly addNameRange     '1.0.5',
48 silly addNameRange     '1.0.5-moved' ] ]
49 silly addNamed cson-safe@1.0.5
50 verbose addNamed "1.0.5" is a plain semver version for cson-safe
51 silly mapToRegistry name cson-safe
52 silly mapToRegistry using default registry
53 silly mapToRegistry registry https://registry.npmjs.org/
54 silly mapToRegistry uri https://registry.npmjs.org/cson-safe
55 verbose addRemoteTarball https://registry.npmjs.org/cson-safe/-/cson-safe-1.0.5.tgz not in flight; adding
56 verbose addRemoteTarball [ 'https://registry.npmjs.org/cson-safe/-/cson-safe-1.0.5.tgz',
56 verbose addRemoteTarball   '3feb83d9349d3a7b1e4d2fa73acaafdfe423efe3' ]
57 info retry fetch attempt 1 at 10:02:18
58 info attempt registry request try #1 at 10:02:18
59 http fetch GET https://registry.npmjs.org/cson-safe/-/cson-safe-1.0.5.tgz
60 verbose request using bearer token for auth
61 http fetch 200 https://registry.npmjs.org/cson-safe/-/cson-safe-1.0.5.tgz
62 silly fetchAndShaCheck shasum 3feb83d9349d3a7b1e4d2fa73acaafdfe423efe3
63 verbose addTmpTarball /tmp/npm-10255-95c4e651/registry.npmjs.org/cson-safe/-/cson-safe-1.0.5.tgz not in flight; adding
64 verbose addTmpTarball already have metadata; skipping unpack for cson-safe@1.0.5
65 silly cache afterAdd cson-safe@1.0.5
66 verbose afterAdd /home/phw/.npm/cson-safe/1.0.5/package/package.json not in flight; writing
67 verbose afterAdd /home/phw/.npm/cson-safe/1.0.5/package/package.json written
68 silly rollbackFailedOptional Starting
69 silly rollbackFailedOptional Finishing
70 silly runTopLevelLifecycles Starting
71 silly runTopLevelLifecycles Finishing
72 silly install printInstalled
73 verbose stack Error: Error extracting /home/phw/.npm/cson-safe/1.0.4/package.tgz archive: ENOENT, open '/home/phw/.npm/cson-safe/1.0.4/package.tgz'
73 verbose stack     at ReadStream.<anonymous> (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:276:10)
73 verbose stack     at ReadStream.emit (events.js:107:17)
73 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:179:14
73 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:16
73 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
74 verbose cwd /home/phw/tmp/nodetest
75 error Linux 4.1.6-1-ARCH
76 error argv "node" "/usr/bin/npm" "install" "cson-safe"
77 error node v0.12.7
78 error npm  v3.3.3
79 error code EREADFILE
80 error Error extracting /home/phw/.npm/cson-safe/1.0.4/package.tgz archive: ENOENT, open '/home/phw/.npm/cson-safe/1.0.4/package.tgz'
81 error If you need help, you may report this error at:
81 error     <https://github.com/npm/npm/issues>
82 verbose exit [ 1, true ]
```

**Comment by phw** [comment]
Just realized this package was renamed. `npm install cson-parser` succeeds in both npm 2 and 3. So maybe more a bug in npm than the package
