### ISSUE TITLE
Bug: empty object and JSDOC style commenting

### ISSUE THREAD

**Issue by aaarichter** [groupon/cson-parser#54]
There is some sort of bug in the parser when an empty object is set inside a single cson file

works:
```cson
###
# tests
###
EN: {}
```

fails:
```cson
###
# tests
###
{}
```

Console output
```bash
SyntaxError: Syntax error on line 1, column 1: One top level value expected
  at nodeTransforms.Block (/Users/arichter/repositories/sls/node_modules/cson-parser/lib/parse.js:82:15)
  at transformNode (/Users/arichter/repositories/sls/node_modules/cson-parser/lib/parse.js:207:12)
  at Object.parse (/Users/arichter/repositories/sls/node_modules/cson-parser/lib/parse.js:213:12)
```

**Comment by aaarichter** [comment]
The problem seems to be happening in the coffee-script's `lexter.tokenizer( )` function at https://github.com/jashkenas/coffeescript/blob/65c35e05a18bef4e302e6fd29c5d0783dd0b8363/src/coffee-script.coffee#L58

I found a workaround that passes the parser:
```
{
###
# test
###
}
```
